"""add seat grid coordinates for seat map, booking by seat_ids

Revision ID: 4c223daec988
Revises: 9dfa163a5f0a
Create Date: 2026-08-26 15:25:27.187151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c223daec988'
down_revision: Union[str, Sequence[str], None] = '9dfa163a5f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('row_number', sa.Integer(), nullable=False))
    op.add_column('seats', sa.Column('column_number', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_coach_seat_position', 'seats', ['coach_id', 'row_number', 'column_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_coach_seat_position', 'seats', type_='unique')
    op.drop_column('seats', 'column_number')
    op.drop_column('seats', 'row_number')
    # ### end Alembic commands ###
