"""initial schema

Revision ID: 9dfa163a5f0a
Revises: 
Create Date: 2026-08-26 15:05:39.740447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfa163a5f0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('station_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='active_inactive_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_station_code'), 'stations', ['station_code'], unique=True)
    op.create_table('trains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('train_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('train_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='active_inactive_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trains_train_number'), 'trains', ['train_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('CUSTOMER', 'ADMIN', name='user_role'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'INACTIVE', name='user_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('coaches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('train_id', sa.UUID(), nullable=False),
    sa.Column('coach_number', sa.String(length=20), nullable=False),
    sa.Column('coach_type', sa.Enum('1AC', '2AC', '3AC', 'SL', 'CC', name='coach_type'), nullable=False),
    sa.Column('seat_capacity', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('train_id', 'coach_number', name='uq_train_coach_number')
    )
    op.create_index(op.f('ix_coaches_train_id'), 'coaches', ['train_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('train_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='active_inactive_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routes_train_id'), 'routes', ['train_id'], unique=False)
    op.create_table('route_stops',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('departure_time', sa.Time(), nullable=True),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_id', 'station_id', name='uq_route_station'),
    sa.UniqueConstraint('route_id', 'stop_sequence', name='uq_route_stop_sequence')
    )
    op.create_index(op.f('ix_route_stops_route_id'), 'route_stops', ['route_id'], unique=False)
    op.create_index(op.f('ix_route_stops_station_id'), 'route_stops', ['station_id'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('train_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('journey_date', sa.Date(), nullable=False),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'COMPLETED', name='schedule_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['train_id'], ['trains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_schedules_train_journey_date', 'schedules', ['train_id', 'journey_date'], unique=False)
    op.create_table('seats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=False),
    sa.Column('seat_type', sa.Enum('LOWER', 'MIDDLE', 'UPPER', 'SIDE_LOWER', 'SIDE_UPPER', 'SEAT', name='seat_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'seat_number', name='uq_coach_seat_number')
    )
    op.create_index(op.f('ix_seats_coach_id'), 'seats', ['coach_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_reference', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('source_station_id', sa.UUID(), nullable=False),
    sa.Column('destination_station_id', sa.UUID(), nullable=False),
    sa.Column('booking_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'WAITLISTED', 'CANCELLED', name='booking_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destination_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['source_station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_index('ix_bookings_schedule_id', 'bookings', ['schedule_id'], unique=False)
    op.create_index('ix_bookings_user_id', 'bookings', ['user_id'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='feedback_status'), nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_user_id'), 'feedback', ['user_id'], unique=False)
    op.create_table('passengers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('berth_preference', sa.Enum('LOWER', 'MIDDLE', 'UPPER', 'SIDE_LOWER', 'SIDE_UPPER', 'NO_PREFERENCE', name='berth_preference'), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passengers_booking_id'), 'passengers', ['booking_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('payment_reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('UPI', 'CARD', 'NET_BANKING', 'WALLET', name='payment_method'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status'), nullable=False),
    sa.Column('transaction_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_reference')
    )
    op.create_index('ix_payments_booking_id', 'payments', ['booking_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('ticket_number', sa.String(length=30), nullable=False),
    sa.Column('ticket_status', sa.Enum('ACTIVE', 'CANCELLED', name='ticket_status'), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_table('booking_seats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('seat_id', sa.UUID(), nullable=False),
    sa.Column('passenger_id', sa.UUID(), nullable=False),
    sa.Column('fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('RESERVED', 'CONFIRMED', 'CANCELLED', name='booking_seat_status'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['passengers.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['seat_id'], ['seats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_seats_booking_id', 'booking_seats', ['booking_id'], unique=False)
    op.create_index('uq_active_seat_per_schedule', 'booking_seats', ['schedule_id', 'seat_id'], unique=True, postgresql_where=sa.text("status IN ('RESERVED', 'CONFIRMED')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_seat_per_schedule', table_name='booking_seats', postgresql_where=sa.text("status IN ('RESERVED', 'CONFIRMED')"))
    op.drop_index('ix_booking_seats_booking_id', table_name='booking_seats')
    op.drop_table('booking_seats')
    op.drop_table('tickets')
    op.drop_index('ix_payments_booking_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_passengers_booking_id'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_index(op.f('ix_feedback_user_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index('ix_bookings_user_id', table_name='bookings')
    op.drop_index('ix_bookings_schedule_id', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_seats_coach_id'), table_name='seats')
    op.drop_table('seats')
    op.drop_index('ix_schedules_train_journey_date', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_route_stops_station_id'), table_name='route_stops')
    op.drop_index(op.f('ix_route_stops_route_id'), table_name='route_stops')
    op.drop_table('route_stops')
    op.drop_index(op.f('ix_routes_train_id'), table_name='routes')
    op.drop_table('routes')
    op.drop_index(op.f('ix_coaches_train_id'), table_name='coaches')
    op.drop_table('coaches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trains_train_number'), table_name='trains')
    op.drop_table('trains')
    op.drop_index(op.f('ix_stations_station_code'), table_name='stations')
    op.drop_table('stations')
    # ### end Alembic commands ###
